=== FcoReyesV/Intro_Frac/Introduccion_Fracciones/web/xml/Modulo_Profesor_esquema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="modulo_profesor">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="usuario" type="Usuarios" minOccurs="1" maxOccurs="1000"/>
  			</xs:sequence>
		</xs:complexType>
	</xs:element>

		<xs:complexType name="usuario">
	  		<xs:sequence>
	  			<xs:element name="nombre" type="xs:string"/>
	  			<xs:element name="introduccion" type="Introduccion"/>
				<xs:element name="crear_fraccion"  type="Crear_fraccion"/>
				<xs:element name="laboratorio_igualdad" type="Laboratorio_igualdad"/>
	  		</xs:sequence>
 		</xs:complexType>

 		<xs:complexType name="introduccion">
 			<xs:sequence>
 				<xs:element name="creados" type="Creados" maxOccurs="1000"/>
 			</xs:sequence>
 		</xs:complexType>
                
        <xs:complexType name="creados">
 			<xs:sequence>
                                <xs:element name="titulo" type="xs:string"/>
                                <xs:element name="tipo" type="xs:string"/>
 				<xs:element name="contador_contenedores" type="xs:integer"/>
 				<xs:element name="contador_numerador" type="xs:integer"/>
 				<xs:element name="contador_denominador" type="xs:integer"/>
 				<xs:element name="contador_figura" type="xs:integer"/>
 				<xs:element name="codigo_html" type="xs:string"/>
 			</xs:sequence>
 		</xs:complexType>

 		<xs:complexType name="crear_fraccion">
 			<xs:sequence>
 				<xs:element name="nivel_1a" type="xs:integer"/>
                                <xs:element name="nivel_2a" type="xs:integer"/>
                                <xs:element name="nivel_3a" type="xs:integer"/>
                                <xs:element name="nivel_4a" type="xs:integer"/>
                                <xs:element name="nivel_5a" type="xs:integer"/>
                                <xs:element name="nivel_1b" type="xs:integer"/>
                                <xs:element name="nivel_2b" type="xs:integer"/>
                                <xs:element name="nivel_3b" type="xs:integer"/>
                                <xs:element name="nivel_4b" type="xs:integer"/>
                                <xs:element name="nivel_5b" type="xs:integer"/>
 				
 			</xs:sequence>
 		</xs:complexType>

 		<xs:complexType name="laboratorio_igualdad"><!--Solo faltaria el de esta parte-->
 		</xs:complexType>

</xs:schema>

=== FcoReyesV/Intro_Frac/CD/IF_Tomcat/xml/Modulo_Profesor.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><modulo_profesor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Modulo_Profesor_esquema.xsd">
<usuario>
	<nombre>p</nombre>
	<introduccion>
                <creados>
                        <titulo>Ejemplo</titulo>
                        <tipo>RH</tipo>
			<contador_contenedores>5</contador_contenedores>
			<contador_numerador>2</contador_numerador>
			<contador_denominador>2</contador_denominador>
			<contador_figura>2</contador_figura>			
			<contenedor_principal></contenedor_principal>
			<contenedor_objetos_draggables></contenedor_objetos_draggables>
		</creados>               
	</introduccion>
</usuario>
</modulo_profesor>

=== FcoReyesV/Intro_Frac/KEVIN/Introduccion_Fracciones/Introduccion_Fracciones/web/xml/Modulo_Profesor.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><modulo_profesor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Modulo_Profesor_esquema.xsd">
<usuario>
	<nombre></nombre>
        <titulo></titulo>
        <tipo></tipo>
	<contador_contenedores></contador_contenedores>
	<contador_numerador></contador_numerador>
	<contador_denominador></contador_denominador>
	<contador_figura></contador_figura>			
	<contenedor_principal></contenedor_principal>
	<contenedor_objetos_draggables></contenedor_objetos_draggables>              
</usuario>
</modulo_profesor>
