=== FcoReyesV/Intro_Frac/CD/IF_Tomcat/xml/Usuarios_esquema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="login">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="usuario" type="Usuarios" minOccurs="1" maxOccurs="1000"/>
  			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Usuarios">
	  	<xs:sequence>
	  		<xs:element name="nombre" type="xs:string"/>
			<xs:element name="pass"  type="xs:string"/>
			<xs:element name="tipo" type="xs:string"/>
	  	</xs:sequence>
 	</xs:complexType>
</xs:schema>

=== FcoReyesV/Intro_Frac/Introduccion_Fracciones/build/web/xml/Usuarios.xml
<login xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Usuarios_esquema.xsd">
	<usuario>
		<nombre>admin</nombre>
		<pass>admin</pass>
		<tipo>Administrador</tipo>
	</usuario>
<<<<<<< HEAD
        <usuario>
		<nombre>p</nombre>
		<pass>p</pass>
		<tipo>Profesor</tipo>
	</usuario>
=======
>>>>>>> 9ebbf4962abab179cb3f57bdbafeb8910e11f68a
</login>
